export const tasksData = [
  "Create a social media content calendar for the next month",
  "Develop a responsive landing page for a new client",
  "Design a logo for a startup company",
  "Prepare a market analysis report for a client in the tech industry",
  "Optimize product descriptions for SEO",
  "Fix bugs in the latest app release",
  "Plan and organize a product launch event",
  "Conduct user research for a new feature",
  "Write a blog post about industry trends",
  "Update the company website with new case studies",
  "Create email marketing campaign for the holiday season",
  "Develop a mobile app prototype",
  "Design business cards for the sales team",
  "Analyze website traffic and generate a report",
  "Set up Google Ads campaign for a new product",
  "Conduct a competitor analysis for a client",
  "Prepare a financial forecast for the next quarter",
  "Create a video tutorial for the company's software",
  "Organize a team-building workshop",
  "Review and update the company's privacy policy",
  "Develop a chatbot for customer support",
  "Design packaging for a new product line",
  "Write a press release for an upcoming event",
  "Set up a CRM system for the sales team",
  "Conduct A/B testing for the website's homepage",
  "Create a presentation for a client meeting",
  "Develop a content strategy for the next quarter",
  "Design a newsletter template",
  "Optimize the checkout process for the e-commerce site",
  "Prepare a training session for new employees",
  "Create a customer feedback survey",
  "Develop a dashboard for tracking key performance indicators (KPIs)",
  "Design a billboard advertisement for a new campaign",
  "Write a script for a promotional video",
  "Set up automated email responses for customer inquiries",
  "Conduct a usability test for the mobile app",
  "Create a style guide for the brand",
  "Develop a feature roadmap for the next year",
  "Design a trade show booth for an upcoming event",
  "Write a whitepaper on industry best practices",
  "Optimize the company's LinkedIn profile",
  "Create a referral program for existing customers",
  "Develop a gamification system for user engagement",
  "Design a infographic for a blog post",
  "Prepare a pitch deck for investors",
  "Set up a retargeting campaign on Facebook",
  "Conduct a SWOT analysis for a new product",
  "Create a disaster recovery plan for IT systems",
  "Design a new onboarding process for users",
  "Write a case study for a successful client project",
  "Develop a loyalty program for repeat customers",
  "Optimize the company's Google My Business listing",
  "Create a series of Instagram Stories for a campaign",
  "Design a new icon set for the mobile app",
  "Write a technical documentation for the API",
  "Set up a webinar for lead generation",
  "Conduct a training session on data privacy",
  "Create a competitor pricing analysis report",
  "Develop a feature to integrate with third-party tools",
  "Create a customer satisfaction survey",
  "Develop a feature to enable two-factor authentication",
  "Design a banner ad for a new product launch",
  "Write a script for a podcast episode",
  "Set up a referral tracking system",
  "Conduct a heatmap analysis for the website",
  "Create a brand voice and tone guide",
  "Develop a feature to export data to CSV",
  "Design a new user interface for the mobile app",
  "Write a product description for a new item",
  "Optimize the website for mobile devices",
  "Create a series of TikTok videos for brand awareness",
  "Develop a feature to schedule social media posts",
  "Design a new email signature for employees",
  "Write a thank-you email for new subscribers",
  "Set up a live chat support system",
  "Conduct a survey to gather customer preferences",
  "Create a competitor analysis spreadsheet",
  "Develop a feature to enable dark mode",
  "Design a new icon for the app's settings menu",
  "Write a FAQ page for the website",
  "Optimize the website's loading speed",
  "Create a LinkedIn ad campaign for lead generation",
  "Develop a feature to enable push notifications",
  "Design a new loading animation for the app",
  "Write a welcome email for new users",
  "Set up a system for tracking employee performance",
  "Conduct a focus group to test a new product idea",
  "Create a roadmap for the next product release",
  "Develop a feature to enable offline mode",
  "Design a new packaging design for a product",
  "Write a script for a customer testimonial video",
  "Optimize the website's meta tags for SEO",
  "Create a Pinterest board for seasonal promotions",
  "Develop a feature to enable voice search",
  "Design a new dashboard for analytics",
  "Write a blog post about customer success stories",
  "Set up a system for tracking inventory levels",
  "Conduct a survey to measure brand awareness",
  "Create a guide for using the company's product",
  "Develop a feature to enable multi-language support",
  "Design a new landing page for a webinar",
  "Write a script for a training video",
  "Optimize the website's URL structure for SEO",
  "Create a YouTube channel for the brand",
  "Develop a feature to enable user profiles",
  "Design a new set of emojis for the app",
  "Write a press release for a new partnership",
  "Set up a system for tracking customer feedback",
  "Conduct a usability test for the website",
  "Create a guide for onboarding new employees",
  "Develop a feature to enable in-app purchases",
  "Design a new set of stickers for messaging apps",
  "Write a script for a product demo video",
  "Optimize the website's schema markup for SEO",
  "Create a Facebook group for customer engagement",
  "Develop a feature to enable screen sharing",
  "Design a new set of illustrations for the website",
  "Write a blog post about industry innovations",
  "Set up a system for tracking project milestones",
  "Conduct a survey to gather employee feedback",
  "Create a guide for troubleshooting common issues",
  "Develop a feature to enable real-time collaboration",
  "Design a new set of avatars for user profiles",
  "Write a script for a company culture video",
  "Optimize the website's alt text for images",
  "Create a Twitter thread about a product launch",
  "Develop a feature to enable file sharing",
  "Design a new set of icons for the website",
  "Write a blog post about customer retention strategies",
  "Set up a system for tracking customer churn",
  "Conduct a survey to measure customer loyalty",
  "Create a guide for using the company's API",
  "Develop a feature to enable video calls",
  "Design a new set of animations for the app",
  "Write a script for a behind-the-scenes video",
  "Optimize the website's internal linking structure",
  "Create a LinkedIn post about a company milestone",
  "Develop a feature to enable task automation",
  "Design a new set of badges for user achievements",
  "Write a blog post about productivity tips",
  "Set up a system for tracking sales leads",
  "Conduct a survey to gather user feedback",
  "Create a guide for integrating third-party tools",
  "Develop a feature to enable location tracking",
  "Design a new set of filters for photos",
  "Write a script for a customer onboarding video",
  "Optimize the website's breadcrumb navigation",
  "Create a Instagram Reel for a product demo",
  "Develop a feature to enable calendar syncing",
  "Design a new set of themes for the app",
  "Write a blog post about remote work best practices",
  "Set up a system for tracking customer support tickets",
  "Conduct a survey to measure employee satisfaction",
  "Create a guide for setting up the product",
  "Develop a feature to enable data encryption",
  "Design a new set of widgets for the dashboard",
  "Write a script for a company values video",
  "Optimize the website's 404 error page",
  "Create a TikTok challenge for brand engagement",
  "Develop a feature to enable voice commands",
  "Design a new set of templates for emails",
  "Write a blog post about industry trends in 2024",
  "Create a customer journey map for the sales process",
  "Develop a feature to enable multi-user collaboration",
  "Design a new set of icons for the mobile app",
  "Write a script for a product unboxing video",
  "Set up a system for tracking customer lifetime value",
  "Conduct a survey to measure customer satisfaction",
  "Create a guide for using the company's analytics tools",
  "Develop a feature to enable data visualization",
  "Design a new set of illustrations for social media posts",
  "Write a blog post about the future of AI in business",
  "Optimize the website's mobile navigation menu",
  "Create a series of Instagram carousel posts",
  "Develop a feature to enable recurring payments",
  "Design a new set of avatars for team members",
  "Write a script for a company anniversary video",
  "Set up a system for tracking employee attendance",
  "Conduct a survey to gather feedback on a new feature",
  "Create a guide for setting up two-factor authentication",
  "Develop a feature to enable offline access to data",
  "Design a new set of stickers for social media stories",
  "Write a blog post about the benefits of remote work",
  "Optimize the website's call-to-action buttons",
  "Create a YouTube video series for product tutorials",
  "Develop a feature to enable drag-and-drop functionality",
  "Design a new set of icons for the website's footer",
  "Write a script for a customer success story video",
  "Set up a system for tracking customer referrals",
  "Conduct a survey to measure brand loyalty",
  "Create a guide for integrating payment gateways",
  "Develop a feature to enable real-time notifications",
  "Design a new set of animations for the website",
  "Write a blog post about the importance of cybersecurity",
  "Optimize the website's search functionality",
  "Create a LinkedIn article about industry trends",
  "Develop a feature to enable bulk actions",
  "Design a new set of templates for presentations",
  "Write a script for a product comparison video",
  "Set up a system for tracking project budgets",
  "Conduct a survey to gather feedback on customer support",
  "Create a guide for using the company's CRM system",
  "Develop a feature to enable data export to PDF",
  "Design a new set of illustrations for email campaigns",
  "Write a blog post about the rise of e-commerce",
  "Optimize the website's footer links for SEO",
  "Create a series of Facebook ads for a new product",
  "Develop a feature to enable user-generated content",
  "Design a new set of icons for the app's navigation",
  "Write a script for a team introduction video",
  "Set up a system for tracking employee performance reviews",
  "Conduct a survey to measure customer engagement",
  "Create a guide for setting up email automation",
  "Develop a feature to enable data filtering",
  "Design a new set of animations for the mobile app",
  "Write a blog post about the future of work",
  "Optimize the website's image compression",
  "Create a TikTok video series for brand awareness",
  "Develop a feature to enable multi-language support",
  "Design a new set of templates for social media posts",
  "Write a script for a product feature highlight video",
  "Set up a system for tracking customer retention rates",
  "Conduct a survey to gather feedback on the website",
  "Create a guide for using the company's project management tools",
  "Develop a feature to enable data import from CSV",
  "Design a new set of illustrations for the app's onboarding",
  "Write a blog post about the impact of automation",
  "Optimize the website's header for faster loading",
  "Create a series of Twitter polls for audience engagement",
  "Develop a feature to enable user role management",
  "Design a new set of icons for the app's settings",
  "Write a script for a company culture highlight video",
  "Set up a system for tracking customer acquisition costs",
  "Conduct a survey to measure employee engagement",
  "Create a guide for setting up a knowledge base",
  "Develop a feature to enable data sorting",
  "Design a new set of animations for the website's homepage",
  "Write a blog post about the benefits of AI in marketing",
  "Optimize the website's video embedding for SEO",
  "Create a series of Instagram Stories for a product launch",
  "Develop a feature to enable multi-device syncing",
  "Design a new set of templates for email newsletters",
  "Write a script for a product demo for social media",
  "Set up a system for tracking customer support response times",
  "Conduct a survey to gather feedback on the mobile app",
  "Create a guide for using the company's analytics dashboard",
  "Develop a feature to enable data backup",
  "Design a new set of illustrations for the website's blog",
  "Write a blog post about the future of digital marketing",
  "Optimize the website's pop-up forms for conversions",
  "Create a YouTube video series for customer testimonials",
  "Develop a feature to enable user activity tracking",
  "Design a new set of icons for the app's profile section",
  "Write a script for a company milestone celebration video",
  "Set up a system for tracking employee training progress",
  "Conduct a survey to measure customer trust in the brand",
  "Create a guide for setting up a customer feedback system",
  "Develop a feature to enable data archiving",
  "Design a new set of animations for the app's loading screen",
  "Write a blog post about the importance of data privacy",
  "Optimize the website's exit-intent pop-ups",
  "Create a series of LinkedIn posts for thought leadership",
  "Develop a feature to enable multi-currency support",
  "Design a new set of templates for case studies",
  "Write a script for a product launch countdown video",
];

export const projectsData = [
  "Facebook Ads Campaign Optimization",
  "Google Ads Performance Review",
  "Website SEO Overhaul",
  "E-commerce Checkout Process Improvement",
  "Social Media Content Strategy",
  "Email Marketing Automation Setup",
  "Mobile App User Onboarding Redesign",
  "Customer Retention Program Launch",
  "Product Launch Marketing Plan",
  "CRM System Migration",
  "LinkedIn Lead Generation Campaign",
  "Instagram Influencer Partnership Strategy",
  "YouTube Video Content Series",
  "TikTok Viral Campaign Development",
  "Website Speed Optimization Project",
  "Customer Feedback Analysis Initiative",
  "Sales Funnel Optimization",
  "Landing Page A/B Testing",
  "Brand Identity Redesign",
  "Employee Training Program Development",
  "Data Privacy Compliance Audit",
  "Customer Support Chatbot Implementation",
  "Product Packaging Redesign",
  "Market Research for New Product Line",
  "Competitor Analysis Report",
  "Blog Content Calendar Creation",
  "Pay-Per-Click (PPC) Campaign Management",
  "Customer Loyalty Program Revamp",
  "Event Marketing Strategy",
  "Trade Show Booth Design",
  "Corporate Social Responsibility Initiative",
  "Employee Engagement Survey Analysis",
  "Website Accessibility Compliance Check",
  "Mobile App Performance Optimization",
  "Cloud Infrastructure Migration",
  "Customer Journey Mapping",
  "Sales Team Training Program",
  "Product Demo Video Production",
  "Customer Onboarding Process Improvement",
  "Social Media Ad Creative Refresh",
  "Email Newsletter Template Redesign",
  "Website User Experience (UX) Audit",
  "Customer Segmentation Analysis",
  "Lead Nurturing Campaign Development",
  "Product Pricing Strategy Review",
  "Customer Satisfaction Survey Implementation",
  "Content Marketing Strategy Development",
  "Affiliate Marketing Program Launch",
  "Influencer Marketing Campaign Planning",
  "Website Conversion Rate Optimization",
  "Customer Support Training Program",
  "Product Feature Usability Testing",
  "Brand Awareness Campaign",
  "Local SEO Strategy Implementation",
  "E-commerce Product Catalog Optimization",
  "Social Media Community Management",
  "Customer Testimonial Video Series",
  "Website Security Audit",
  "Employee Onboarding Process Redesign",
  "Customer Churn Analysis",
  "Product Return Process Optimization",
  "Google My Business Profile Optimization",
  "Customer Data Platform Integration",
  "Sales Pipeline Management Review",
  "Product Launch Press Release",
  "Website Content Localization",
  "Customer Support Knowledge Base Creation",
  "Social Media Crisis Management Plan",
  "Email List Segmentation Strategy",
  "Product Review Collection Campaign",
  "Website Heatmap Analysis",
  "Customer Referral Program Launch",
  "Sales Script Development",
  "Product Packaging Sustainability Initiative",
  "Customer Feedback Loop Implementation",
  "Website Cookie Policy Update",
  "Mobile App Push Notification Strategy",
  "Customer Success Story Development",
  "Social Media Hashtag Strategy",
  "Email Campaign Performance Analysis",
  "Product Demo Webinar Series",
  "Website Blog Redesign",
  "Customer Support Response Time Optimization",
  "Sales Collateral Creation",
  "Product Feature Roadmap Planning",
  "Customer Engagement Strategy",
  "Website Pop-Up Form Optimization",
  "Mobile App Gamification Features",
  "Customer Onboarding Email Sequence",
  "Social Media Ad Targeting Optimization",
  "Email Marketing List Cleanup",
  "Product Usability Feedback Collection",
  "Website Exit-Intent Popup Implementation",
  "Customer Loyalty Reward Program",
  "Sales Team Performance Review",
  "Product Launch Influencer Outreach",
  "Customer Support Live Chat Implementation",
  "Website FAQ Section Update",
  "Mobile App User Feedback Analysis",
  "Customer Journey Personalization",
  "Social Media Post Scheduling Automation",
  "Email Marketing Template Refresh",
  "Product Packaging Cost Reduction",
  "Website 404 Error Page Redesign",
  "Customer Support Ticket System Upgrade",
];
